config-version = "2.7"

bind = "0.0.0.0:25565"

motd = "<#00ffff>Eaglercraft Server"

show-max-players = 100

online-mode = false

player-info-forwarding-mode = "none"

[servers]
lobby = "168.119.78.155:55376"

try = [
  "lobby"
]
