config-version = "2.7"

bind = "0.0.0.0:25565"

motd = "StolenCraft Eaglercraft Server"

show-max-players = 100

online-mode = false

player-info-forwarding-mode = "none"

announce-forge = false

kick-existing-players = false

ping-passthrough = "disabled"

sample-players-in-ping = false

enable-player-address-logging = false


[servers]

stolencraft = "168.119.78.155:55376"

try = [
    "stolencraft"
]


[forced-hosts]

"stolencraft.falixsrv.me" = [
    "stolencraft"
]


[advanced]

compression-threshold = 256

compression-level = -1

login-ratelimit = 3000

connection-timeout = 5000

read-timeout = 30000

tcp-fast-open = false

bungee-plugin-message-channel = true

show-max-players = 100

accepts-transfers = false


[query]

enabled = false

port = 25565

map = "Velocity"
